/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ngo Nhan
 */
public class QLNhanVienView extends javax.swing.JFrame {

    /**
     * Creates new form QLNhanVienView
     */
    DefaultTableModel defaultTableModel;
    QuanLyNhanVien quanLyNhanVien = new QuanLyNhanVien();
    public QLNhanVienView() {
        initComponents();
        ArrayList<NhanVien> list =quanLyNhanVien.getListNhanVien();
        loadData(list);
        lblBanGhi.setText(layThongTin());
        
    }
    void loadData(ArrayList<NhanVien> listNhanVien){
        defaultTableModel = (DefaultTableModel) tblBang.getModel();
        defaultTableModel.setRowCount(0);
        for (NhanVien nhanVien : listNhanVien) {
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNV(),
                nhanVien.getTenNV(),
                nhanVien.getTuoi(),
                nhanVien.geteMail(),
                nhanVien.getLuong()
            });
        }
        DongHo dongho = new DongHo(lblTime);
        Thread t1 = new Thread(dongho);
        t1.start();
    }
     public String layThongTin(){
        int index =tblBang.getSelectedRow();
         return "Record:"+(index +1)+ " of "+ quanLyNhanVien.getListNhanVien().size();
     }
     public void fillNhanVien(int index){
         txtma.setText(quanLyNhanVien.getListNhanVien().get(index).getMaNV());
         txtTen.setText(quanLyNhanVien.getListNhanVien().get(index).getTenNV());
         txtEmail.setText(quanLyNhanVien.getListNhanVien().get(index).geteMail());
         txtTuoi.setText(String.valueOf(quanLyNhanVien.getListNhanVien().get(index).getTuoi()));
         txtLuong.setText(String.valueOf(quanLyNhanVien.getListNhanVien().get(index).getLuong()));
     }
     public void fistNV(){
         int index = 0;
        
        duLieu(index);
     }

    private void duLieu(int index) {
        
        tblBang.setRowSelectionInterval(index, index);
        fillNhanVien(index);
        lblBanGhi.setText(layThongTin());
    }
     public void lastNV(){
         int index = quanLyNhanVien.getListNhanVien().size() -1;
        duLieu(index);
     }
     public void preNV(){
         int index = tblBang.getSelectedRow();
         if (index ==0) {
             lastNV();
         } else {
             index --;
             
         }
         duLieu(index);
     }
     public void nextNV(){
         int index = tblBang.getSelectedRow();
         if (index ==quanLyNhanVien.getListNhanVien().size()-1) {
             fistNV();
         } else {
             index ++;
             
         }
         duLieu(index);
     } 
     public NhanVien readFrom(){    
         
         return new NhanVien(txtma.getText(), txtTen.getText(),Integer.parseInt(txtTuoi.getText()),txtEmail.getText(),Double.parseDouble(txtLuong.getText()));
     }
     public NhanVien timTheoMa(String id){
         ArrayList<NhanVien> list = quanLyNhanVien.getListNhanVien();
         for (NhanVien nhanVien : list) {
             if (nhanVien.getMaNV().equalsIgnoreCase(id)) {
                 return nhanVien;
             }
         }
         return null;
     }
     public void capNhat(NhanVien newNhanVien){
         NhanVien nv1 = timTheoMa(newNhanVien.getMaNV() );
         if (nv1!=null) {
             nv1.setTenNV(newNhanVien.getTenNV());
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrew = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        lblBanGhi = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setText("MÃ NHÂN VIÊN");

        jLabel3.setText("HỌ VÀ TÊN");

        jLabel4.setText("TUỔI");

        jLabel5.setText("EMAIL");

        jLabel6.setText("LƯƠNG");

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ", "HỌ VÀ TÊN", "TUỔI", "EMAIL", "LƯƠNG"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNew.setText("New");
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrew.setText("<<");
        btnPrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrewActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        lblBanGhi.setForeground(new java.awt.Color(255, 51, 51));
        lblBanGhi.setText("Record 1 of 10");

        lblTime.setForeground(new java.awt.Color(255, 51, 51));
        lblTime.setText("00:00 AM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrew, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBanGhi))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirst)
                            .addComponent(btnPrew)
                            .addComponent(btnNext)
                            .addComponent(btnLast)
                            .addComponent(lblBanGhi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        String ma;
        // TODO add your handling code here:
//        String ma ="";
        txtma.setText(String.valueOf(ma =""));
        String ten ="";
        txtTen.setText(String.valueOf(ten));
        String tuoi ="";             
        txtTuoi.setText(String.valueOf(tuoi));
        String email ="";
        txtEmail.setText(String.valueOf(email));
        String luong ="";
        txtLuong.setText(String.valueOf(luong));
         
    }//GEN-LAST:event_btnNewMouseClicked

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        // TODO add your handling code here:
        int i = tblBang.getSelectedRow();
        
        String ma =(String) tblBang.getValueAt(i, 0);
        txtma.setText(ma);
        String ten = (String) tblBang.getValueAt(i, 1);
        txtTen.setText(ten);
        Integer tuoi = (Integer) tblBang.getValueAt(i, 2);
        txtTuoi.setText(tuoi.toString());
        String email = (String) tblBang.getValueAt(i, 3);
        txtEmail.setText(email);
        Double luong = (Double) tblBang.getValueAt(i, 4);
        txtLuong.setText(luong.toString());
        lblBanGhi.setText(layThongTin());
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        int index =tblBang.getSelectedRow();
 if (index==-1) {
     String ma = txtma.getText();
        ArrayList<NhanVien> listKetQua = quanLyNhanVien.getListNhanVien();
        for (NhanVien nhanVien : listKetQua) {
            if (nhanVien.getMaNV().equals(ma)) {
                JOptionPane.showMessageDialog(this, "Ma khong duoc trung");
                return;
            }
        }
        
        String ten = txtTen.getText();
        Integer tuoi = Integer.parseInt(txtTuoi.getText());
        String email = txtEmail.getText();
        Double luong = Double.parseDouble(txtLuong.getText());
        NhanVien nhanVien = new NhanVien(ma, ten, tuoi, email, luong);
        
        if (ma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ma khong duoc trong!");
//        } else if(ma.equals()){
//            JOptionPane.showMessageDialog(this, "Ma khong duoc trung!");
        } else if(tuoi <16 || tuoi >65){
            JOptionPane.showMessageDialog(this, "Tuoi trong khoang 16-65!");
        }else if (luong <5000000){
            JOptionPane.showMessageDialog(this, "Luong phai tren 5M!");
        }
//        else if(email.contains("@")){
//            JOptionPane.showMessageDialog(this, "Email khong dung dinh dang!");
//        }
        else{       
        Boolean checkSave = quanLyNhanVien.addNew(nhanVien);
        if (checkSave) {
            JOptionPane.showMessageDialog(this, "Them thanh cong!");
            loadData(quanLyNhanVien.getListNhanVien());
        }
        } 
        
 }else{
     capNhat(readFrom());
     loadData(quanLyNhanVien.getListNhanVien());
     JOptionPane.showMessageDialog(this, "Update thanh cong");
 }
//        String ma = txtma.getText();
//        ArrayList<NhanVien> listKetQua = quanLyNhanVien.getListNhanVien();
//        for (NhanVien nhanVien : listKetQua) {
//            if (nhanVien.getMaNV().equals(ma)) {
//                JOptionPane.showMessageDialog(this, "Ma khong duoc trung");
//                return;
//            }
//        }
//        
//        String ten = txtTen.getText();
//        Integer tuoi = Integer.parseInt(txtTuoi.getText());
//        String email = txtEmail.getText();
//        Double luong = Double.parseDouble(txtLuong.getText());
//        NhanVien nhanVien = new NhanVien(ma, ten, tuoi, email, luong);
//        
//        if (ma.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Ma khong duoc trong!");
////        } else if(ma.equals()){
////            JOptionPane.showMessageDialog(this, "Ma khong duoc trung!");
//        } else if(tuoi <16 || tuoi >65){
//            JOptionPane.showMessageDialog(this, "Tuoi trong khoang 16-65!");
//        }else if (luong <5000000){
//            JOptionPane.showMessageDialog(this, "Luong phai tren 5M!");
//        }
////        else if(email.contains("@")){
////            JOptionPane.showMessageDialog(this, "Email khong dung dinh dang!");
////        }
//        else{       
//        Boolean checkSave = quanLyNhanVien.addNew(nhanVien);
//        if (checkSave) {
//            JOptionPane.showMessageDialog(this, "Them thanh cong!");
//            loadData(quanLyNhanVien.getListNhanVien());
//        }
//        }
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        String ma = txtma.getText();
        Boolean check = quanLyNhanVien.delete(ma);
        
        if (check && !ma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Xoa thanh cong.");
            loadData(quanLyNhanVien.getListNhanVien());
        }else{
        JOptionPane.showMessageDialog(this, "Can phai nhap ma.");
    }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        // TODO add your handling code here:
        String find = txtma.getText();
        
        ArrayList<NhanVien> ketQua = quanLyNhanVien.search(find);
        if (ketQua.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong co nhan vien nay");
        }else
        loadData(ketQua);
        for (NhanVien nhanVien : ketQua) {
            String ten = nhanVien.getTenNV();
        txtTen.setText(ten);
        Integer tuoi = nhanVien.getTuoi();
        txtTuoi.setText(tuoi.toString());
        String email = nhanVien.geteMail();
        txtEmail.setText(email);
        Double luong = nhanVien.getLuong();
        txtLuong.setText(luong.toString());
        }
        

    }//GEN-LAST:event_btnFindMouseClicked
    
    public void ghifile() throws IOException{
        File file = new File("data.txt");
        if (!file.exists()) {
            file.createNewFile();
        }
        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        
       ArrayList<NhanVien> list = quanLyNhanVien.getListNhanVien();
        for (NhanVien nhanVien : list) {
            oos.writeObject(nhanVien);
        }
        oos.close();
        fos.close();
        
    }
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        try {
            // TODO add your handling code here:
            // ghi file va thoat
            ghifile();
            
        } catch (IOException ex) {
            Logger.getLogger(QLNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked
    
    public void docFile() throws FileNotFoundException, IOException, ClassNotFoundException{
        File file = new File("data.txt");
        if (!file.exists()) {
            System.out.println("File ko tim thay");
            return;
        }
        FileInputStream fis = new FileInputStream(file);
        
        ObjectInputStream ois = new ObjectInputStream(fis) ;
        ArrayList<NhanVien> list = new ArrayList<>();
        while (fis.available()>0) {            
            list.add((NhanVien) ois.readObject());
        }
      ois.close();
      fis.close();
        loadData(list);
    }
    private void btnOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenMouseClicked
        try {
            // TODO add your handling code here:
            docFile();
        } catch (IOException ex) {
            Logger.getLogger(QLNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLNhanVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        fistNV();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        lastNV();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrewActionPerformed
        // TODO add your handling code here:
        preNV();
    }//GEN-LAST:event_btnPrewActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        nextNV();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPrew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanGhi;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTuoi;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables
}
